### PR TITLE
Expose animation structs

### PR DESCRIPTION
**Pull request by FredrikNoren**
Some more minor improvements

### CODE REVIEW

**Comment by Eljay** [comment]
Thanks, I can make you a collaborator on this if you like as I have no intention of maintaining it currently.

**Comment by FredrikNoren** [comment]
@Eljay sure would be awesome. Can you add to the -sys one as well?

**Comment by FredrikNoren** [comment]
Also what's needed to push it crates.io? Can you add me for push rights to that too?

**Comment by Eljay** [comment]
Sure, added you to both repos. For crates.io you need to sign up with your github account first, then I can add you.

**Comment by FredrikNoren** [comment]
Alright, I've created an account there

**Comment by Eljay** [comment]
Done, you should now be able to publish both crates.

**Comment by FredrikNoren** [comment]
Thanks!

**Pull request merged**
